-- --------------------------------------------------------------------------
-- -------------------------------lab-sql-joins------------------------------
-- --------------------------------------------------------------------------
-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the sakila database:

-- 1. List the number of films per category.
SELECT
	c.name AS category,
	COUNT(f.film_id) AS number_of_films
FROM
	film f
JOIN
	film_category fc ON f.film_id = fc.film_id
JOIN
	category c ON fc.category_id = c.category_id
GROUP BY
	c.name
ORDER BY
	number_of_films DESC;


-- --------------------------------------------------------------------------
-- 2. Retrieve the store ID, city, and country for each store.

SELECT 
    s.store_id,
    ci.city,
    co.country
FROM 
    store s
JOIN 
    address a ON s.address_id = a.address_id
JOIN 
    city ci ON a.city_id = ci.city_id
JOIN 
    country co ON ci.country_id = co.country_id;

-- --------------------------------------------------------------------------
-- 3. Calculate the total revenue generated by each store in dollars.

SELECT
	s.store_id,
	SUM(p.amount) as total_revenue
FROM
	payment p
JOIN
	rental r ON r.rental_id = p.rental_id
JOIN 
	inventory i ON i.inventory_id = r.inventory_id
JOIN
	store s ON s.store_id = i.store_id
GROUP BY
	s.store_id
ORDER BY total_revenue DESC;


-- --------------------------------------------------------------------------
-- 4. Determine the average running time of films for each category.

SELECT
	c.name AS category,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM
	film f
JOIN
	film_category fc ON fc.film_id = f.film_id
JOIN
	category c ON c.category_id = fc.category_id
GROUP BY
	c.name
ORDER BY average_running_time DESC;
